title:
  firstname: Podshara
  lastname: Chanrungmaneekul
author:
  name: Podshara Chanrungmaneekul
  email: pc45<span>at</span>rice<span>dot</span>edu
description: > # this means to ignore newlines until "show_excerpts:"
  This is my personal web page containing my personal and contact information.
  This page is also a collection of the projects that I have worked on.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    scholar_userid: UA5y84MAAAAJ
    orcid: 0009-0007-2858-3729

    linkedin_username: p-chanrun
    # new social links
    dblp_url: https://dblp.org/pid/339/9008.html
    arxiv: ''
    research_gate_profile: Podshara-Chanrungmaneekul
    ieee_id: 37089894385


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
# theme: minima

collections:
  projects:
    output: false
  experiences:
    output: false
  publications:
    output: false

plugins:
 - jekyll-seo-tag
