title:
  firstname: Podshara
  lastname: Chanrungmaneekul
author:
  name: Podshara Chanrungmaneekul
  email: pc45<span>at</span>rice<span>dot</span>edu
description: > # this means to ignore newlines until "show_excerpts:"
  This is my personal web page containing my personal and contact information.
  This page is also a collection of the projects that I have worked on.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: chanwut_k
    github:  chanwutk
    googlescholar: Q9OsSU8AAAAJ
    orcid: 0000-0002-2884-2221
    dblp: 284/8705
    arxiv: ''
    semanticscholar: 2047935706
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: chanwut-k
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: chanwutk
    #   instance: gitlab.cs.washington.edu
    # - username: chanwutk
    #   instance: gitlab.com
    
    # new social links
    github_username: chanwutk
    linkedin_username: chanwut-k
    x_username: chanwut_k
    scholar_userid: Q9OsSU8AAAAJ
    orcid_id: 0000-0002-2884-2221
    # dblp_url: https://dblp.org/pid/284/8705.html
    # arxiv: ''
    # semanticscholar_id: 2047935706
    # research_gate_profile: Chanwut_Kittivorawong
    # ieee_id: 37088661022
    # acm_id: 99660995561
    # scopus_id: 57221955432
    # stackoverflow_id: 9174154/chanwutk


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
# theme: minima

collections:
  projects:
    output: false
  experiences:
    output: false
  publications:
    output: false

plugins:
 - jekyll-seo-tag
